# Generated by Django 6.0 on 2026-01-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('value', models.BinaryField()),
            ],
            options={
                'verbose_name': 'KV',
                'verbose_name_plural': 'KVs',
                'constraints': [models.UniqueConstraint(models.F('queue'), models.F('key'), name='unique_kv_queue_key')],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue', models.CharField(max_length=255)),
                ('data', models.BinaryField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'ordering': ['timestamp'],
                'indexes': [models.Index(models.F('queue'), models.F('timestamp'), name='idx_schedule_queue_timestamp')],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue', models.CharField(max_length=255)),
                ('data', models.BinaryField()),
                ('priority', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-priority', 'id'],
                'indexes': [models.Index(models.OrderBy(models.F('priority'), descending=True), models.F('id'), name='idx_task_priority_id')],
            },
        ),
    ]
